name: Laravel-Next.js CI/CD Pipeline

on:
  push:
    branches: [ main, feature/cicd ]
  pull_request:
    branches: [ main, feature/cicd ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Laravel Backend
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip

    - name: Install Composer Dependencies
      working-directory: ./EpicTales-backend
      run: composer install --prefer-dist --no-progress

    - name: Laravel Setup
      working-directory: ./EpicTales-backend
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Laravel Tests
      working-directory: ./EpicTales-backend
      run: php artisan test

    # Next.js Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install Node Dependencies
      working-directory: ./epictales-frontend
      run: npm ci

    - name: Next.js Build
      working-directory: ./epictales-frontend
      run: npm run build

    # - name: Next.js Tests
    #   working-directory: ./epictales-frontend
    #   run: npm test
