name: Laravel-Next.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    # Laravel Backend
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
    
    - name: Install Composer Dependencies
      working-directory: ./backend
      run: composer install --prefer-dist --no-progress

    - name: Laravel Setup
      working-directory: ./backend
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan migrate --force
    
    - name: Laravel Tests
      working-directory: ./backend
      run: php artisan test
    
    # Next.js Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Install Node Dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Next.js Build
      working-directory: ./frontend
      run: npm run build
    
    - name: Next.js Tests
      working-directory: ./frontend
      run: npm test
    
    # Deploy (Example using Railway)
    - name: Install Railway CLI
      if: github.ref == 'refs/heads/main'
      run: npm i -g @railway/cli

    - name: Deploy Backend
      if: github.ref == 'refs/heads/main'
      working-directory: ./backend
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy Frontend
      if: github.ref == 'refs/heads/main'
      working-directory: ./frontend
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}